#!/bin/bash
set -euo pipefail

rhythm_forge_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
if ! "$rhythm_forge_dir/check-dependencies" --notify; then
  exit 1
fi
exec python3 "$rhythm_forge_dir/rhythm_forge.py" "$@"
